# Generated by Django 5.2 on 2025-06-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudarriendo',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudarriendo',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudarriendo',
            name='token_webpay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudarriendo',
            name='fecha_evento',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='solicitudarriendo',
            unique_together={('fecha_evento', 'hora_inicio', 'hora_fin')},
        ),
    ]
