# Generated by Django 5.2 on 2025-06-30 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendos', '0002_solicitudarriendo_hora_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudarriendo',
            name='comprobante_pago',
        ),
        migrations.AlterField(
            model_name='solicitudarriendo',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20),
        ),
    ]
