# Generated by Django 5.2 on 2025-07-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendos', '0003_remove_solicitudarriendo_comprobante_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudarriendo',
            name='comprobante_pago',
            field=models.ImageField(blank=True, help_text='Imagen del comprobante de pago del arriendo', null=True, upload_to='comprobantes_arriendo/'),
        ),
    ]
