# Generated by Django 5.2 on 2025-07-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendos', '0004_solicitudarriendo_comprobante_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudarriendo',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('PAGADO', 'Pagado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20),
        ),
    ]
