# Generated by Django 5.2 on 2025-07-03 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arriendos', '0005_alter_solicitudarriendo_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudarriendo',
            name='token_webpay',
        ),
    ]
