# Generated by Django 5.2 on 2025-07-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendos', '0006_remove_solicitudarriendo_token_webpay'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='solicitudarriendo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='solicitudarriendo',
            name='comprobante_pago_base64',
            field=models.TextField(blank=True, help_text='Imagen del comprobante en formato base64', null=True),
        ),
        migrations.AlterField(
            model_name='solicitudarriendo',
            name='hora_fin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='solicitudarriendo',
            name='hora_inicio',
            field=models.TimeField(),
        ),
        migrations.RemoveField(
            model_name='solicitudarriendo',
            name='comprobante_pago',
        ),
    ]
