# Generated by Django 5.2 on 2025-07-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendos', '0007_alter_solicitudarriendo_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudarriendo',
            name='cantidad_asistentes',
            field=models.PositiveIntegerField(),
        ),
    ]
