# Generated by Django 5.2 on 2025-06-21 02:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoResidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Certificado de Residencia', editable=False, max_length=100)),
                ('plantilla', models.FileField(help_text='Plantilla DOCX del certificado', upload_to='plantillas/certificado_residencia/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx'])])),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio del certificado en CLP', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado'), ('ARCHIVADO', 'Archivado')], default='PUBLICADO', max_length=20)),
                ('campos_requeridos', models.JSONField(default=list, help_text='Campos del formulario en formato JSON')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Certificado',
                'verbose_name_plural': 'Configuración Certificado',
            },
        ),
        migrations.CreateModel(
            name='SolicitudCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos', models.JSONField(default=dict, help_text='Datos proporcionados para el certificado')),
                ('documento', models.FileField(blank=True, null=True, upload_to='certificados_generados/%Y/%m/%d/')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('REEMBOLSADO', 'Reembolsado')], default='PENDIENTE', max_length=20)),
                ('codigo_transaccion', models.CharField(blank=True, help_text='Código de transacción de Webpay', max_length=100)),
                ('respuesta_webpay', models.JSONField(blank=True, help_text='Respuesta completa de Webpay', null=True)),
                ('estado_documento', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('GENERADO', 'Generado'), ('ENTREGADO', 'Entregado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('fecha_generacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_certificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Certificado',
                'verbose_name_plural': 'Solicitudes de Certificados',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='TransaccionWebpay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('INICIADA', 'Iniciada'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('REVERSADA', 'Reversada')], max_length=20)),
                ('respuesta', models.JSONField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transaccion', to='documentos.solicitudcertificado')),
            ],
            options={
                'verbose_name': 'Transacción Webpay',
                'verbose_name_plural': 'Transacciones Webpay',
            },
        ),
        migrations.AddIndex(
            model_name='solicitudcertificado',
            index=models.Index(fields=['estado_pago', 'estado_documento'], name='documentos__estado__686caa_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudcertificado',
            index=models.Index(fields=['codigo_transaccion'], name='documentos__codigo__83831c_idx'),
        ),
    ]
