# Generated by Django 5.2 on 2025-06-05 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, choices=[('ORDINARIA', 'Ordinaria'), ('EXTRAORDINARIA', 'Extraordinaria'), ('EMERGENCIA', 'Emergencia')], max_length=50, null=True)),
                ('fecha', models.DateTimeField()),
                ('lugar', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('convocante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reuniones_convocadas', to=settings.AUTH_USER_MODEL)),
                ('participantes', models.ManyToManyField(related_name='reuniones_participantes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reuniones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente de validación'), ('VALIDADA', 'Validada')], default='BORRADOR', max_length=20)),
                ('firmado_presidente', models.BooleanField(default=False)),
                ('firmado_secretario', models.BooleanField(default=False)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actas_creadas', to=settings.AUTH_USER_MODEL)),
                ('reunion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acta', to='reuniones.reunion')),
            ],
        ),
    ]
