# Generated by Django 5.2 on 2025-06-30 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reuniones', '0002_eliminar_participantes'),
    ]

    operations = [
    ]
