# Generated by Django 5.2 on 2025-06-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniones', '0003_force_sync'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reunion',
            name='convocante',
        ),
        migrations.RemoveField(
            model_name='reunion',
            name='creada_en',
        ),
        migrations.RemoveField(
            model_name='reunion',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='reunion',
            name='titulo',
            field=models.CharField(default='Reunión sin título', max_length=200),
        ),
        migrations.AlterField(
            model_name='reunion',
            name='motivo',
            field=models.CharField(choices=[('ORDINARIA', 'Ordinaria'), ('EXTRAORDINARIA', 'Extraordinaria'), ('INFORMATIVA', 'Informativa')], default='ORDINARIA', max_length=50),
        ),
        migrations.DeleteModel(
            name='Acta',
        ),
    ]
