# Generated by Django 5.2 on 2025-07-01 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialValidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_validacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_validado', models.ForeignKey(help_text='Usuario que fue validado', on_delete=django.db.models.deletion.CASCADE, related_name='validaciones', to=settings.AUTH_USER_MODEL)),
                ('validado_por', models.ForeignKey(help_text='Usuario que realizó la validación (presidente)', on_delete=django.db.models.deletion.CASCADE, related_name='validaciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Validación',
                'verbose_name_plural': 'Historial de Validaciones',
                'ordering': ['-fecha_validacion'],
            },
        ),
    ]
