# Generated by Django 5.2 on 2025-06-30 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('tipo', models.CharField(choices=[('ANUNCIO', 'Anuncio General'), ('EVENTO', 'Evento'), ('AVISO', 'Aviso Importante'), ('NOTICIA', 'Noticia'), ('PERDIDO', 'Objeto Perdido'), ('VENTA', 'Venta/Intercambio')], default='ANUNCIO', max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('PAUSADA', 'Pausada'), ('ARCHIVADA', 'Archivada')], default='ACTIVA', max_length=20)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen para la publicación (opcional)', null=True, upload_to='publicaciones/%Y/%m/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_evento', models.DateTimeField(blank=True, null=True)),
                ('lugar_evento', models.CharField(blank=True, max_length=200, null=True)),
                ('es_destacada', models.BooleanField(default=False)),
                ('fecha_expiracion', models.DateTimeField(blank=True, help_text='Fecha después de la cual la publicación se archiva automáticamente', null=True)),
                ('vistas', models.PositiveIntegerField(default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['-es_destacada', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(max_length=500)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_publicaciones', to=settings.AUTH_USER_MODEL)),
                ('comentario_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='publicaciones.comentariopublicacion')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='publicaciones.publicacion')),
            ],
            options={
                'verbose_name_plural': 'Comentarios',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='MeGustaPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='me_gustas_publicaciones', to=settings.AUTH_USER_MODEL)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='me_gustas', to='publicaciones.publicacion')),
            ],
            options={
                'verbose_name_plural': 'Me Gustas',
                'unique_together': {('publicacion', 'usuario')},
            },
        ),
    ]
