# Generated by Django 5.2 on 2025-06-30 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='megustapublicacion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='megustapublicacion',
            name='publicacion',
        ),
        migrations.RemoveField(
            model_name='megustapublicacion',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='ComentarioPublicacion',
        ),
        migrations.DeleteModel(
            name='MeGustaPublicacion',
        ),
    ]
