# Generated by Django 5.2 on 2025-06-30 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_alter_megustapublicacion_unique_together_and_more'),
    ]

    operations = [
    ]
