# Generated by Django 5.2 on 2025-07-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0003_auto_20250630_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.TextField(blank=True, help_text='Imagen para la publicación en formato base64 o URL (opcional)', null=True),
        ),
    ]
