# Generated by Django 5.2 on 2025-05-30 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comunidad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactoautoridad',
            name='junta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidad.juntavecinos'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='junta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidad.juntavecinos'),
        ),
        migrations.AddField(
            model_name='sedecomunitaria',
            name='junta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='comunidad.juntavecinos'),
        ),
    ]
