# Generated by Django 5.2 on 2025-06-05 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anuncio',
            options={'permissions': [('publicar_anuncio', 'Puede publicar anuncios')]},
        ),
    ]
